# Generated by Django 5.2.1 on 2025-06-03 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioElectricidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('hora', models.IntegerField(verbose_name='Hora')),
                ('precio', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Precio (€/kWh)')),
                ('estado', models.CharField(default='desconocido', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Precio de Electricidad',
                'verbose_name_plural': 'Precios de Electricidad',
                'ordering': ['fecha', 'hora'],
                'unique_together': {('fecha', 'hora')},
            },
        ),
    ]
