# Generated by Django 5.2.1 on 2025-06-03 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity_prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hour', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=8)),
                ('status', models.CharField(default='unknown', max_length=10)),
            ],
            options={
                'ordering': ['date', 'hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
        migrations.DeleteModel(
            name='PrecioElectricidad',
        ),
    ]
